# Generated by Django 4.1.7 on 2023-04-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mli_app', '0003_alter_patient_address_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
