# Generated by Django 4.1.7 on 2023-04-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mli_app', '0004_customuser_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date',
        ),
    ]
